### ISSUE TITLE
Increase Timing For Magisk Bootloop Saver

### ISSUE THREAD

**Issue by B0j4ngl35** [HuskyDG/huskydg.github.io#2]
How do I increase the timing of disabling all of the modules from the default that is set @ 50s [double or triple the timing]?

**Comment by HuskyDG** [comment]
That's not what you are thinking.
This modules will check zygote id every 15s, if zygote id of 3 stage of zygote checking is same. It will exit.
If not, check for the next 15s zygote id, if they are not the same too then the script will disable all modules and exit

**Comment by B0j4ngl35** [comment]
Thanks.
